# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'XQDemo' do

pod "AFNetworking", "~> 2.0"
pod "ReactiveCocoa", "~>2.1.8"

end

target 'XQDemoTests' do

end

